CREATE TABLE IF NOT EXISTS process_firmware_download_backup (
  id int(11) NOT NULL AUTO_INCREMENT,
  line varchar(50) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  generator_name varchar(50) NOT NULL,
  artist varchar(50) DEFAULT NULL,
  lightstick varchar(64) DEFAULT NULL,
  serial varchar(20) DEFAULT NULL,
  device_guid binary(16) NOT NULL,
  board_name varchar(100) DEFAULT NULL,
  last_log_id int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pfd_device_guid (device_guid),
  KEY ix_pfd_gn_time (generator_name, updated_at),
  KEY ix_pfd_gn_serial (generator_name, serial),
  KEY idx_pfd_last_log_id (last_log_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS process_firmware_download_log_backup (
  id int(11) NOT NULL AUTO_INCREMENT,
  line varchar(50) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  generator_name varchar(50) NOT NULL,
  artist varchar(50) DEFAULT NULL,
  lightstick varchar(64) DEFAULT NULL,
  serial varchar(20) DEFAULT NULL,
  device_guid binary(16) DEFAULT NULL,
  row_id varchar(100) DEFAULT NULL,
  evk_time varchar(100) DEFAULT NULL,
  write_check int(11) DEFAULT 0,
  board_name varchar(100) DEFAULT NULL,
  result varchar(20) NOT NULL,
  disable_protect_flash_r varchar(100) DEFAULT NULL,
  disable_protect_flash_v varchar(100) DEFAULT NULL,
  erase_firmware_k_r varchar(100) DEFAULT NULL,
  erase_firmware_k_v varchar(100) DEFAULT NULL,
  calib_fre_offset_2498mhz_hz_r varchar(100) DEFAULT NULL,
  calib_fre_offset_2498mhz_hz_v varchar(100) DEFAULT NULL,
  tx_cnt_2498mhz_r varchar(100) DEFAULT NULL,
  tx_cnt_2498mhz_v varchar(100) DEFAULT NULL,
  rx_cnt_2498mhz_r varchar(100) DEFAULT NULL,
  rx_cnt_2498mhz_v varchar(100) DEFAULT NULL,
  tx_power_2498mhz_db_r varchar(100) DEFAULT NULL,
  tx_power_2498mhz_db_v varchar(100) DEFAULT NULL,
  rx_power_2498mhz_r varchar(100) DEFAULT NULL,
  rx_power_2498mhz_v varchar(100) DEFAULT NULL,
  calib_fre_offset_2398mhz_hz_r varchar(100) DEFAULT NULL,
  calib_fre_offset_2398mhz_hz_v varchar(100) DEFAULT NULL,
  tx_cnt_2398mhz_r varchar(100) DEFAULT NULL,
  tx_cnt_2398mhz_v varchar(100) DEFAULT NULL,
  rx_cnt_2398mhz_r varchar(100) DEFAULT NULL,
  rx_cnt_2398mhz_v varchar(100) DEFAULT NULL,
  tx_power_2398mhz_db_r varchar(100) DEFAULT NULL,
  tx_power_2398mhz_db_v varchar(100) DEFAULT NULL,
  rx_power_2398mhz_r varchar(100) DEFAULT NULL,
  rx_power_2398mhz_v varchar(100) DEFAULT NULL,
  erase_mac_k_r varchar(100) DEFAULT NULL,
  erase_mac_k_v varchar(100) DEFAULT NULL,
  write_firmware_err_addr_r varchar(100) DEFAULT NULL,
  write_firmware_err_addr_v varchar(100) DEFAULT NULL,
  write_mac_hb_r varchar(100) DEFAULT NULL,
  write_mac_hb_v varchar(100) DEFAULT NULL,
  write_mac_lb_r varchar(100) DEFAULT NULL,
  write_mac_lb_v varchar(100) DEFAULT NULL,
  write_freoffset_r varchar(100) DEFAULT NULL,
  write_freoffset_v varchar(100) DEFAULT NULL,
  check_firmware_err_addr_r varchar(100) DEFAULT NULL,
  check_firmware_err_addr_v varchar(100) DEFAULT NULL,
  check_mac_lb_r varchar(100) DEFAULT NULL,
  check_mac_lb_v varchar(100) DEFAULT NULL,
  read_mac_lb_value_r varchar(100) DEFAULT NULL,
  read_mac_lb_value_v varchar(100) DEFAULT NULL,
  check_freoffset_r varchar(100) DEFAULT NULL,
  check_freoffset_v varchar(100) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY ix_pfdl_gn_time (generator_name, created_at),
  KEY ix_pfdl_gn_serial (generator_name, serial),
  KEY ix_pfdl_result_time (result, created_at),
  KEY idx_pfdl_device_guid (device_guid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
