USE lightstickv2_data;

CREATE TABLE IF NOT EXISTS process_mac_check (
  id int(11) NOT NULL AUTO_INCREMENT,
  line varchar(50) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  generator_name varchar(50) NOT NULL,
  artist varchar(50) NOT NULL,
  lightstick varchar(64) NOT NULL,
  serial varchar(20) NOT NULL,
  mac_address varchar(50) NOT NULL,
  device_guid binary(16) DEFAULT NULL,
  device_sn_raw binary(16) DEFAULT NULL,
  device_sn_enc binary(16) DEFAULT NULL,
  last_log_id int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pmc_mac_address (mac_address),
  KEY ix_pmc_gn_time (generator_name, updated_at),
  KEY ix_pmc_gn_mac (generator_name, mac_address),
  KEY ix_pmc_gn_ser (generator_name, serial DESC),
  KEY idx_pmc_device_guid (device_guid),
  KEY idx_pmc_gen_guid (generator_name, device_guid),
  KEY idx_pmc_last_log_id (last_log_id),
  KEY idx_pmc_device_sn_raw (device_sn_raw),
  KEY idx_pmc_device_sn_enc (device_sn_enc),
  KEY idx_pmc_gen_device_sn_raw (generator_name, device_sn_raw)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS process_mac_check_backup (
  id int(11) NOT NULL AUTO_INCREMENT,
  line varchar(50) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  generator_name varchar(50) NOT NULL,
  artist varchar(50) NOT NULL,
  lightstick varchar(64) NOT NULL,
  serial varchar(20) NOT NULL,
  mac_address varchar(50) NOT NULL,
  device_guid binary(16) DEFAULT NULL,
  device_sn_raw binary(16) DEFAULT NULL,
  device_sn_enc binary(16) DEFAULT NULL,
  last_log_id int(11) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pmc_mac_address (mac_address),
  KEY ix_pmc_gn_time (generator_name, updated_at),
  KEY ix_pmc_gn_mac (generator_name, mac_address),
  KEY ix_pmc_gn_ser (generator_name, serial DESC),
  KEY idx_pmc_device_guid (device_guid),
  KEY idx_pmc_gen_guid (generator_name, device_guid),
  KEY idx_pmc_last_log_id (last_log_id),
  KEY idx_pmc_bak_device_sn_raw (device_sn_raw),
  KEY idx_pmc_bak_device_sn_enc (device_sn_enc),
  KEY idx_pmc_bak_gen_device_sn_raw (generator_name, device_sn_raw)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS process_mac_check_log (
  id int(11) NOT NULL AUTO_INCREMENT,
  line varchar(50) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  generator_name varchar(50) NOT NULL,
  artist varchar(50) NOT NULL,
  lightstick varchar(64) NOT NULL,
  serial varchar(20) NOT NULL,
  mac_address varchar(50) NOT NULL,
  device_guid binary(16) DEFAULT NULL,
  device_sn_raw binary(16) DEFAULT NULL,
  device_sn_enc binary(16) DEFAULT NULL,
  fw_version varchar(10) DEFAULT NULL,
  device_name varchar(50) DEFAULT NULL,
  result varchar(20) NOT NULL,
  write_result varchar(20) DEFAULT NULL,
  description varchar(255) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY ix_pmcl_gn_time (generator_name, updated_at),
  KEY ix_pmcl_gn_mac (generator_name, mac_address),
  KEY ix_pmcl_gn_ser (generator_name, serial),
  KEY idx_pmcl_device_guid (device_guid),
  KEY idx_pmcl_gen_guid (generator_name, device_guid),
  KEY idx_pmcl_result_time (result, updated_at),
  KEY idx_pmcl_device_sn_raw (device_sn_raw),
  KEY idx_pmcl_device_sn_enc (device_sn_enc),
  KEY idx_pmcl_gen_device_sn_raw (generator_name, device_sn_raw)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS process_mac_check_log_backup (
  id int(11) NOT NULL AUTO_INCREMENT,
  line varchar(50) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  generator_name varchar(50) NOT NULL,
  artist varchar(50) NOT NULL,
  lightstick varchar(64) NOT NULL,
  serial varchar(20) NOT NULL,
  mac_address varchar(50) NOT NULL,
  device_guid binary(16) DEFAULT NULL,
  device_sn_raw binary(16) DEFAULT NULL,
  device_sn_enc binary(16) DEFAULT NULL,
  fw_version varchar(10) DEFAULT NULL,
  device_name varchar(50) DEFAULT NULL,
  result varchar(20) NOT NULL,
  write_result varchar(20) DEFAULT NULL,
  description varchar(255) DEFAULT NULL,
  PRIMARY KEY (id),
  KEY ix_pmcl_gn_time (generator_name, updated_at),
  KEY ix_pmcl_gn_mac (generator_name, mac_address),
  KEY ix_pmcl_gn_ser (generator_name, serial),
  KEY idx_pmcl_device_guid (device_guid),
  KEY idx_pmcl_gen_guid (generator_name, device_guid),
  KEY idx_pmcl_result_time (result, updated_at),
  KEY idx_pmcl_bak_device_sn_raw (device_sn_raw),
  KEY idx_pmcl_bak_device_sn_enc (device_sn_enc),
  KEY idx_pmcl_bak_gen_device_sn_raw (generator_name, device_sn_raw)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

CREATE TABLE IF NOT EXISTS process_mac_check_scan_log (
  id int(11) NOT NULL AUTO_INCREMENT,
  line varchar(50) DEFAULT NULL,
  mac_address varchar(50) NOT NULL,
  mac_no_colon varchar(12) NOT NULL,
  raw text NOT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (id),
  KEY idx_pmcsl_mac (mac_address),
  KEY idx_pmcsl_line_date (line, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
